default: &default
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: postgresql
  host: localhost
  port: 5432
  database: msi_directory_test
  username: msi
  password: ism
  min_messages: notice

production:
  <<: *default
  adapter: postgresql
  host: localhost
  port: 5432
  database: msi_directory_prod
  username: msi
  password: ism
  min_messages: notice
