default: &default
  encoding: unicode
  pool: 5
  timeout: 5000

msi-directory-app-dev:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

msi-directory-app-test:
  <<: *default
  adapter: postgresql
  host: 172.31.52.93
  port: 5432
  database: msi_directory_test
  username: msi
  password: ism
  min_messages: notice

msi-directory-app-prod:
  <<: *default
  adapter: postgresql
  host: 172.31.52.93
  port: 5432
  database: msi_directory_prod
  username: msi
  password: ism
  min_messages: notice

msi-directory-app-pentest:
  <<: *default
  adapter: postgresql
  host: 172.31.55.82
  port: 5432
  database: msi_directory_prod
  username: msi
  password: ism
  min_messages: notice
